### PR TITLE
Fixes invalid login crash

### PR DESCRIPTION
**Pull request by Mctalian**
Apparently in all of my tests, I never mistyped the credentials :wolf:

### CODE REVIEW

**Comment by Mctalian** [comment]
@monotkate @YashdalfTheGray @davethenipper @LongArmMcGee @bcbrennecke 

Take a look, but I'm going to merge it once it's green since it's a server crash and blocking @monotkate

**Comment by Mctalian** [comment]
Super weird... I don't see this error locally...

**Comment by Mctalian** [comment]
@YashdalfTheGray is there a way that travis has different jshint configuration than local builds?

**Comment by YashdalfTheGray** [comment]
No way, it's got the same configuration since it's all reading from .jshintrc just like your jshint should be. What version is your jshint sitting at? We might have a version mismatch?

**Comment by YashdalfTheGray** [comment]
@Mctalian go ahead and merge this and I'm going to chalk it up to a freak accident for now, if it happens again, I'll look more into it.

**Comment by Mctalian** [comment]
I'll check when I get to Yash's

**Comment by Mctalian** [comment]
And by Yash, I meant braun. Can't get to MKE that fast

**Comment by YashdalfTheGray** [comment]
Haha, sounds good. Can I merge this so that our codebase is stable-ish?

**Comment by Mctalian** [comment]
Yes please. I'm getting food :P

**Pull request merged**
