### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Mctalian**
Added npm install gulp-cli -g to the installation.

### CODE REVIEW

**Comment by YashdalfTheGray** [comment]
So I can just merge this PR and all of your changes come with it?

**Comment by Mctalian** [comment]
No I tried to chop them up I'm pretty sure in case you wanted to only have
one or some of them.

**Comment by Mctalian** [comment]
Hmm... apparently I'm wrong. I made this PR then moved forward with a few things before I realized I couldn't cherry-pick commit PRs without making a branch. I will remake this later.

**Comment by YashdalfTheGray** [comment]
Oh okay, so I can keep this PR live for documentation purposes but we'll kill this and merge the new ones. 

I'll tag a new alpha tonight before I go to bed/get on my next flight.

**Comment by Mctalian** [comment]
I rolled this in with the config script PR.

**Pull request closed without merging**
