### PR TITLE
Replaced time properties with timeCreated

### PR DESCRIPTION
**Pull request by Mctalian**
This takes care of the first part of #265.

The existing data still needs to be updated.

Please check off when finished reviewing:
- [x] 1st Reviewer (@alanlgirard)
- [x] 2nd Reviewer (@davethenipper, @YashdalfTheGray)

### CODE REVIEW

**Comment by Mctalian** [comment]
@alanlgirard, @davethenipper

**Comment by alanlgirard** [comment]
Looks good.  Approved!

**Comment by monotkate** [comment]
oooo, I like this checking off approval thing....

**Comment by YashdalfTheGray** [comment]
Do I get to approve?

**Comment by Mctalian** [comment]
Yeah that's fine. I'll just change it to generic "1st Reviewer, 2nd Reviewer" in the future. I tagged those two because they found it/investigated it with me.

**Comment by YashdalfTheGray** [comment]
Oh okay, I'll let them approve it then. I was just going to approve the code on face value, @davethenipper's approval probably would be worth more.

**Comment by davethenipper** [comment]
I really like the approval check boxes.

Also, Approved.

**Pull request merged**
