### PR TITLE
Ideas being returned multiple times when searching tags [With git fixes]

### PR DESCRIPTION
**Pull request by Daviddt17**
I handled all the git issues I had with #242

### CODE REVIEW

**Comment by Daviddt17** [comment]
@YashdalfTheGray @Mctalian @alanlgirard @monotkate @LongArmMcGee @bcbrennecke

**Comment by Mctalian** [comment]
Approved.

**Comment by YashdalfTheGray** [comment]
Approved, well done my good sir! +1 git for you.

**Comment by Daviddt17** [comment]
Merged!

**Pull request merged**
