### PR TITLE
rebase to master

### PR DESCRIPTION
**Pull request by YashdalfTheGray**

### CODE REVIEW

**Comment by Mctalian** [comment]
FYI I'm doing a huge backend overhaul right now. So I'd stick to the front
end for now if I were you. I got really motivated last night.

**Comment by YashdalfTheGray** [comment]
What's the backend overhaul going to bring?

**Comment by YashdalfTheGray** [comment]
I was going to work on the toasts.

**Comment by Mctalian** [comment]
Database schema adherence and trying to clean the files up. Make it DRY,
etc.

**Comment by YashdalfTheGray** [comment]
Oh snap! Alright, I like that. Hey, thanks for picking up the slack after that mongo conversion man. I owe you a huge one!

**Comment by Mctalian** [comment]
Not a problem, learned a lot!

**Pull request merged**
