### PR TITLE
IE Compatibilities

### LINKED ISSUE #185: About Page is Stretched on Internet Explorer
About Page is Stretched on Internet Explorer.

### PR DESCRIPTION
**Pull request by Mctalian**
The following are now IE compatible (somehow they stopped being compatible at some point).
* About Page and closes #185
* Login Dialog RA-INT message
* Team Tab
* Edit Idea
* Add Idea

### CODE REVIEW

**Comment by Mctalian** [comment]
@YashdalfTheGray @bcbrennecke @alanlgirard @davethenipper @LongArmMcGee @monotkate @Daviddt17 Reviews welcome and appreciative

**Comment by alanlgirard** [comment]
Looks good.  Maybe one day Rockwell will switch from IE being the default browser....Nope never going to happen :frowning: 

Approved! :+1:

**Comment by monotkate** [comment]
On the about page it doesn't wrap the names of the group like it does in other browsers so they just kind of drop off the page.  Problem?

**Comment by monotkate** [comment]
Rest of it looks good :+1:

**Comment by Mctalian** [comment]
@monotkate Yeah, I did notice that. I wasn't sure I liked the wrapping behavior and I was trying to think of the best way to handle the whole "team" portion of the about page.

I have an idea, let me try something...

**Comment by Mctalian** [comment]
Alright, the about page should be better. I also added some IE compatibility changes for the All Ideas view. (I really wanted to change the name to that as well, but I elected not to with @YashdalfTheGray having a large delivery coming and he may have had to touch that file. Merges are much harder when the file disappears or gets moved).

I also noticed if a new idea is submitted while someone was viewing the All Ideas page, the new idea didn't appear. So I fixed that.

Also, closes #147  just for fun.

**Comment by Mctalian** [comment]
@monotkate can you check the list of developers in the about page to see if this new solution is better?

I will merge on your approval.

**Comment by monotkate** [comment]
:100: Love it.

Approved if you get someone else to give me second approval on my PR :grinning:

**Comment by Mctalian** [comment]
I'll see what I can do! :moneybag:

**Pull request merged**
