### PR TITLE
Indicates which Login Credentials

### LINKED ISSUE #178: No Login Credential Indication
The user does not know what login credentials to use.  We should inform them it supports their single sign on.

Side note: Saying that we store their credentials is wrong.

### PR DESCRIPTION
**Pull request by Mctalian**
Closes #178

There is now a bit of help text that lets users know which credentials to use when logging in.

image

### CODE REVIEW

**Comment by Mctalian** [comment]
@bcbrennecke approves, he walked by moments after I put up this PR

**Comment by monotkate** [comment]
personally I would adjust to say something about Rockwell credentials or something, but otherwise windows would work

**Comment by LongArmMcGee** [comment]
Looks reasonable

**Comment by alanlgirard** [comment]
I don't know if I would word it as Windows Credentials.  I know there are some macs in the company(MFT) so it is probably better to use Rockwell or RA-INT in the description.

**Comment by Mctalian** [comment]
Rockwell uses at least 2 logins. So even that is misleading unfortunately.

**Comment by monotkate** [comment]
So basically there's no good way to clarify? lol.  What are we drawing from for login then?  Which Rockwell login?

**Comment by YashdalfTheGray** [comment]
How about "Use your Rockwell SSO"? I know for a fact that most people know what that is because a recent training mentioned something like that.

**Comment by LongArmMcGee** [comment]
Never heard of SSO. I would assume it means single sign on? Wouldn't
'RA-Int Domain' be the most descriptive?

**Comment by Mctalian** [comment]
RA-INT is probably the best we're going to get because single sign on to me
could also be the SharePoint login (ADFS).

**Comment by LongArmMcGee** [comment]
Settled.

**Comment by YashdalfTheGray** [comment]
Approved!

**Comment by Mctalian** [comment]
Verbal approvals from @alanlgirard and @bcbrennecke. Plus @YashdalfTheGray's approval above. I'm merging.

**Pull request merged**
