### PR TITLE
ideaView Title Change

### LINKED ISSUE #268: ideaView title jank
This is unacceptable. 

screen shot 2016-01-29 at 9 53 03 am

(Only) this is acceptable

screen shot 2016-01-29 at 9 54 33 am

### PR DESCRIPTION
**Pull request by monotkate**
Aiming to fix #268 

If people hate this change, that's fine, but resizing the window messed with the edit icons quite a bit, and I didn't see an easy way to group them using span.  Ultimate I found this a cleaner look anyway, with some more emphasis on the title without consuming much more space.

Logged out: idea created by not edited
image

Logged in: idea also edited
image

- [x] Review 1 ( @Mctalian or @alanlgirard )
- [x] Reviewer 2 ( @YashdalfTheGray )

### CODE REVIEW

**Comment by Mctalian** [comment]
Hmm... center text. I'm going to let this one sink in for a bit.  Center
text is hit and miss typically. I'll give an actually productive review
later, just wanted to actually send a notification that I looked at it this
time :P

**Comment by alanlgirard** [comment]
I am not crazy about the center text also.  I like it for smaller screens but maybe only do the center align on layout-sm or layout-md depending on which size starts showing the display issue.  I think we should keep the row layout for bigger resolutions.

**Comment by alanlgirard** [comment]
Also to test the extremes use a title that takes up the most space possible such as 150 Ws with no spaces

**Comment by Mctalian** [comment]
I would prefer to add spaces to see how it handles actual breaks. If it
splits in the middle of a word, we have another problem to solve in
addition to this.

**Comment by alanlgirard** [comment]
It is set to `word-wrap: break-word` right now so if there are spaces it should not break up a word.  When I was messing with the word-wraping I alternated between

`WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW`

and

`This is a long title. This is a long title. This is a long title. This is a long title. This is a long title. This is a long title. This is a long one`

**Comment by Mctalian** [comment]
Ok good, try those out :P

**Comment by monotkate** [comment]
I did that just didn't screencap. Ill do that when I get back from walking the dogs. It didn't look terrible.

**Comment by monotkate** [comment]
Centered max title: 
Logged in:
image

Logged out:
image

Alternative:
Logged out:
image

Logged in:
image

**Comment by monotkate** [comment]
image

**Comment by monotkate** [comment]
@Mctalian @alanlgirard check out the screenshots and give me opinions when you get the chance

**Comment by Mctalian** [comment]
If I had to pick between them, I'd pick centered text.

Side note: how do those giant titles look in "all ideas"? Maybe we should
tone down the 150 to like... 60?

**Comment by Mctalian** [comment]
I approve. There isn't an obvious "better option" to me than center text at the moment, so I'd rather not hold this up right now. This fixes the title jank and we'll make sure the next probably iteration doesn't reintroduce title jank.

**Comment by monotkate** [comment]
They don't look terrible, they just '...' when then run out of space.  I've wondered as well if we should tone down the characters though.

**Comment by Mctalian** [comment]
On this page they '...' ? 

image

**Comment by monotkate** [comment]
Oh.  All ideas.  I can read.  I was thinking toolbar.  Yeah...... maybe we should limit characters.

**Comment by monotkate** [comment]
image

**Comment by monotkate** [comment]
Either we wrap text and start columning (like a tumblr search) or we limit much more?

**Comment by Mctalian** [comment]
Something for another issue perhaps, but 30 was too short, I think 150 is too long unless we put ellipses for All Ideas as well.

**Comment by alanlgirard** [comment]
Approved for the title changes.  It at least fixes the problem for right now.  As for the title character limit, 150 might be a little too long.  Lets just open another issue to either reduce the title character count or adjust the all ideas page to wrap/ellipsis.

**Comment by davethenipper** [comment]
I like this fix.  I also like the word wrap for titles, Max had some pretty long titles that make sense.

**Comment by YashdalfTheGray** [comment]
Centered title solved the problem at hand and like it was said above, there isn't a clearly present "alternative" so we'll go with this. Good job on this, @monotkate. I also think we should open another issue for decreasing the idea title limit. I propose 100.

**Comment by monotkate** [comment]
:+1: @YashdalfTheGray next time check the box, I did it for you

**Comment by YashdalfTheGray** [comment]
Sorry, I'll keep that in mind!

**Pull request merged**
