### PR TITLE
Get User Data by ID

### PR DESCRIPTION
**Pull request by Mctalian**
This stores all interactions by user ID instead of User's name. So we query the database by the userId when we need a user's name, email, or username.

### CODE REVIEW

**Comment by LongArmMcGee** [comment]
The c++ dev approves! What is a .js file?

**Comment by davethenipper** [comment]
Approve!!!

**Comment by davethenipper** [comment]
Bobbbbbbbb

**Comment by davethenipper** [comment]
meerrrrggggeee

**Comment by davethenipper** [comment]
stop helping brauny man

**Pull request merged**
