### PR TITLE
Fixed idea being returned multiple times when searching tags

### PR DESCRIPTION
**Pull request by Daviddt17**
This PR addresses issue #230. 

An idea would be returned more than once when a search matched that many number of tags. Simply switched to a traditional for loop so I could break once one of the tags matched.

### CODE REVIEW

**Comment by Mctalian** [comment]
Does this test pass if you add it?

```javascript
it('should only have an idea in the results once', function() {
    var query = "TestTag";
    expect(search(testList, query).length).toEqual(4);
});
```

**Comment by Mctalian** [comment]
Approved pending adding the above test, and fixing tag searching by looking at my most recent comment in #230 talking about back-end stuff.

**Comment by YashdalfTheGray** [comment]
@Daviddt17, any updates on this?

**Comment by Daviddt17** [comment]
Sorry I've been away from the office and this project for so long. I've really been dropping the ball. Anyway, I added the test case that @Mctalian wanted and also added tags to the promise on the server side to make tags searchable. Think that should cover everything. @Mctalian @YashdalfTheGray

**Comment by YashdalfTheGray** [comment]
@Mctalian, does this look larger than it should be to you? It seems like git thinks that those commits on the main master aren't there on the main master branch.

**Comment by Mctalian** [comment]
Yeah... this doesn't look right... I'm not even sure how to fix that.

**Comment by Mctalian** [comment]
Somehow your rebase got messed up or something. Most of the commits showing up in this PR are ones that have already been pushed to master.

**Comment by Daviddt17** [comment]
I am the master of messing up merges! I'll list the steps I took so that we can figure it out.

1. After 8 days of not working on this, I made the changes suggested and committed tonight.
2. Fetched the upstream changes for flintandsteel
3. Rebased with upstream
(I think this is where I messed up)
4. Try to push to my fork but git forces me to pull first as I'm ahead of my fork.
5. After the pull I push and it seems the commits from other users have been rehashed or something

I honestly think I mess this up every time. What is the proper procedure for rebasing?

**Comment by Mctalian** [comment]
Yash won't like this, but typically I open a PR from his master to mine
through the GitHub interface. If I see everyone else's commits and not my
new ones, I succeeded and merge it. If I see my own, I reverse the commits.

It takes the proverbial gun out of your hand, or at least it leaves the
bullets out. Git can be dangerous.

I'd have to see the git commands your issuing in that above process to
diagnose what went wrong.

I compared the minimal hashes of some of the commits and they match, so I'm
still a bit confused on that. I didn't expand the hashes, but I'd be
shocked if the most significant values on those exact commits lined up
perfectly. I think there's a 1/268,435,456 chance that any two given
commits will have the same short hash, let alone two commits that are
essentially duplicates of each other having an exact short hash.

**Comment by Mctalian** [comment]
And when I say "GitHub" above, I literally mean on the web interface in the
browser, not in the desktop app.

**Comment by YashdalfTheGray** [comment]
Bingo, that's it. Never, ever, ever, ever do anything with upstream. You've got a fork, you should be working within your fork and then pushing to master from your local and creating a PR from your master to the main master branch. 

So when you start your work, this is what you do

1. Make sure that your master and the main master have the same number of commits and the last commit matches. If you don't have a PR open, this should always be true anyway. 
2. Run a `git pull origin master`, this will pull down master from your fork. 
3. Make your changes. At this point, consider making another branch that you make your changes on. This way, there is at least a local copy of working code that you can switch back to. 
4. Since you created a branch to work on besides master (this is why it's a good idea), go online and check on your fork. Are there new changes on master? If there are, run another `git pull origin master` to pull new changes down. 
5. Now run a `git merge <your-branch-name>` while on master. This will merge your changes into your local laster branch. 
6. Run a `git push origin master` to push your changes to to your fork. 
7. Create a PR from your master branch to the main master. 

For example, let's say I'm going to work on access tokens. When I start my work, I make sure that my fork and the main repo are at the same commit. Then I run a `git pull origin master` from the terminal to pull the latest master down. At this point, I would create a branch by running `git checkout -b access-tokens-feature`. I would make my changes on that branch. 

Assume that some new code shows up on master right before I'm about to merge my new changes to my local laster branch. Since I'm on a different branch, I run `git checkout master` first and then `git pull origin master` to bring in the new changes. 

Now that I've made my changes on access-tokens-feature and the latest code from the main master is on my local laster branch, I run `git merge access-token-feature` which I'm on master to merge my changes with the new code from the main master branch. 

Then, I get on github, create a PR from my master to the main master. This way, the only thing that's different are the changes that I originally made on the access-tokens-feature branch.

**Comment by YashdalfTheGray** [comment]
What I'm going to have you do is create a new branch off of your master, revert your master back to where the main master is (or some place that we have common history), push your master to make sure, cherry-pick the commits out of your other branch that are useful (your work) and then merge them into your master. Then push your master and create another PR.

**Comment by YashdalfTheGray** [comment]
I created a card in the trello faq for our team for this. I think this is a good workflow description so I wanted to save it somewhere else.

**Comment by Mctalian** [comment]
If you used `git rebase` I do think that's where it messed up. When we say "rebase" that may come from a few of our old ClearCase days. Perhaps we've been using the wrong lingo the whole time. Sorry about that.

I would agree that sitting down with someone to fix this particular scenario is best though if possible.

After my PR goes through, I'll look into testing that work flow and adding to it.

**Comment by Daviddt17** [comment]
I think I *git* it now. Utilizing a branch for work is key. My master branch should be used only for keeping in sync with flintandsteel. When I'm ready for to merge a PR I can just merge with my master and all should be well.

**Comment by Daviddt17** [comment]
What if I revert all the commits that I've made since I started working on this issue, then force pushed that to my repo and started fresh. I don't mind making the changes again since there weren't very many.

**Comment by YashdalfTheGray** [comment]
Yeah, that should work. First create a branch from master and we'll basically "park" that branch. Then checkout master, look into the commit history for the main master and your master, find the commit where they divert, everything before that commit should be the same on both masters, and revert back to that commit using `git revert --hard <git_commit_sha>`. Then create a PR from my master to your master to get the latest code and merge it. Then while staying on master, figure what commit shas represent your changes and run `git cherry-pick <git_commit_sha>` for those commits to bring them back to master. 

if you want, stop by around lunch time and I can help.

**Pull request closed without merging**
