### PR TITLE
gulp generate:data alias

### PR DESCRIPTION
**Pull request by LongArmMcGee**
generate colon data is too long

### CODE REVIEW

**Comment by Mctalian** [comment]
Hahahahahaha

**Comment by Mctalian** [comment]
Looks like you forgot to rebase to latest before submitting this though. You're about 45 commits behind.

**Comment by YashdalfTheGray** [comment]
Yeah, make sure you rebase before turning in a PR. `gulp generate:data` is no longer a valid command with the mongo transition. That being said, well done.

**Comment by YashdalfTheGray** [comment]
Can we close this?

**Comment by Mctalian** [comment]
Yes, if he truly wants this he can do it with an updated PR

**Pull request closed without merging**
