### PR TITLE
Disabling LDAP using the NODE_ENV!

### PR DESCRIPTION
**Pull request by YashdalfTheGray**
So a couple of changes are all rolled up in this PR
* The server now looks for the node environment to decide if to use LDAP or not
* The server reports what environment it is running in
* The `gulp start` command is now broken up into `gulp start:dev` and gulp start:prod`
* Everything in the `server/secrets` folder has been added to the exclusion list for jshint and jscs. 
* The server has hard-coded credentials right now but that'll [change](https://github.com/YashdalfTheGray/flintandsteel/blob/master-author/server/server.js#L128) when mongo goes in.

Reviewers - @Mctalian, @bcbrennecke, @davethenipper

### CODE REVIEW

**Comment by Mctalian** [comment]
Approve! :1:

**Comment by davethenipper** [comment]
Approved

**Comment by bcbrennecke** [comment]
Sounds like a plan Stan

**Comment by YashdalfTheGray** [comment]
Merging.

**Pull request merged**
