### PR TITLE
Fixed errors @mctalian found this morning

### PR DESCRIPTION
**Pull request by bcbrennecke**
-Changed md-content tag to a div in homeview.tpl.html
-Changed www.innovate.com link to a #.
-Added space to the end of filler words to stop concatenation of words

Review me @YashdalfTheGray @Mctalian

### CODE REVIEW

**Comment by YashdalfTheGray** [comment]
:+1:

**Comment by Mctalian** [comment]
The div wasn't the problem, sorry. Revert that change, the problem was inside that element, you have an md-content, the word cloud, and a second md-content. Delete the second md-content and the scroll bar goes away.

**Comment by bcbrennecke** [comment]
@Mctalian , Like that?  If so just merge it in!

**Comment by Mctalian** [comment]
Nope not like that.

**Comment by Mctalian** [comment]
This is what I mean.

```
<md-content layout="row" class="cloud-container-padding">
    <md-content flex="5"></md-content>
    <div id="wordcloud" flex="90"></div>
    <md-content flex="5"></md-content> // Delete this line
</md-content>
```

Because although 5 + 90 + 5 == 100, sometimes (for whatever reason) 100% is slightly larger than the page width and it ends up popping up a scroll bar. So it's best to stay below 100.

Alternatively something like this might work:

```
<md-content layout="row" layout-align="center" class="cloud-container-padding">
    <div id="wordcloud" flex="90"></div>
</md-content>
```

But you'd have to check in a few browsers to ensure compatibility.

**Comment by bcbrennecke** [comment]
@Mctalian This works in chrome, can't get it to go across my network for IE though for some reason, can you check it quick?

**Comment by Mctalian** [comment]
I'll check it this afternoon

**Comment by YashdalfTheGray** [comment]
No. No IE :wink:

**Comment by Mctalian** [comment]
Looks like it works in IE! Nice work. You forgot the layout align center but I don't think it's noticeable

**Comment by Mctalian** [comment]
a.k.a. Approved

**Pull request merged**
