### PR TITLE
LDAP/AD/Single-sign-on!!!!!!

### PR DESCRIPTION
**Pull request by Mctalian**
This does some very minimal LDAP/AD stuff. Basically, it handles the logins. Sign-up link was removed.

There is still some work that we can do to persist logins through page refreshes (if we want to).

We can probably do some other cool stuff as well, but for now, I'm happy with single-sign-on.

In order for this to work on your workstation, you must create a `secrets` folder in the `server` directory. Inside this directory make an ldapAuth.js file. I will provide later guidance via email on what to put inside this file.

Reviewers: @YashdalfTheGray, @davethenipper

### CODE REVIEW

**Comment by Mctalian** [comment]
Oh it also closes #72

**Comment by Mctalian** [comment]
Future reading: https://www.airpair.com/express/posts/expressjs-and-passportjs-sessions-deep-dive very useful.

http://toon.io/understanding-passportjs-authentication-flow/

**Comment by YashdalfTheGray** [comment]
Approved, this looks good, I'm pumped!

**Comment by davethenipper** [comment]
Oh yeah?? Well I'm even more pumped.  APPROVED!

**Pull request merged**
