### PR TITLE
Added OK to logout toast and enabled login on enter

### PR DESCRIPTION
**Pull request by monotkate**
@YashdalfTheGray @Mctalian @bcbrennecke

### CODE REVIEW

**Comment by alanlgirard** [comment]
APPROVED

**Comment by Mctalian** [comment]
Beautifully done. Approved.

Question though, how did adding `type="button"` to the Close button make enter work for the Login button? I have no doubts that it works because I just saw it first hand but I'm curious as to why it works.

**Comment by monotkate** [comment]
http://stackoverflow.com/questions/17551220/angular-ui-dialog-and-form-submit-on-enter-key

Basically, it defaults to enter working, so it was entering on the cancel button.  I changed cancel to be just a button only, so then it went back to doing enter for login.

**Comment by bcbrennecke** [comment]
Approve!

**Pull request merged**
