### PR TITLE
Fixed DialogBackCtrl

### PR DESCRIPTION
**Pull request by monotkate**
I'm pretty sure I'm the one that broke this in the merge confusion between @YashdalfTheGray and I, but I caught it doing a rebase today.  Small fix,  but without it adding and editing a back won't work.

@YashdalfTheGray @alanlgirard @Mctalian

### CODE REVIEW

**Comment by monotkate** [comment]
Wait, I think more than this is broken, at least on mine.  Fixing now + writing tests for it, I'll update this.

**Comment by monotkate** [comment]
ok, writing tests later, this should fix it now, and if it fails the build I have no clue why.....

**Comment by Mctalian** [comment]
It works now right? If so, approved.

**Comment by monotkate** [comment]
yes it does.  Which is a good thing

**Comment by alanlgirard** [comment]
Approved

**Pull request merged**
